### ISSUE TITLE
location_array       [${longitude['host']},${latitude['host']}]                  # Not available

### ISSUE THREAD

**Issue by ytc301** [y-ken/fluent-plugin-geoip#16]
location_array       [${longitude['host']},${latitude['host']}]                  # Not available

```
Starting td-agent: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.57/lib/fluent/config/basic_parser.rb:86:in `parse_error!': got incomplete JSON array configuration at td-agent.conf line 220,9 (Fluent::ConfigParseError)
219:   pos_file /tmp/fluentd--1415859217.pos
220: </source>
     ---------^
    from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.57/lib/fluent/config/literal_parser.rb:235:in `scan_json'
    from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.57/lib/fluent/config/literal_parser.rb:56:in `parse_literal'
    from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.57/lib/fluent/config/v1_parser.rb:120:in `parse_element'
    from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.57/lib/fluent/config/v1_parser.rb:91:in `parse_element'
    from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.57/lib/fluent/config/v1_parser.rb:91:in `parse_element'
    from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.57/lib/fluent/config/v1_parser.rb:40:in `parse!'
    from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.57/lib/fluent/config/v1_parser.rb:30:in `parse'
    from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.57/lib/fluent/config.rb:30:in `parse'
    from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.57/lib/fluent/supervisor.rb:385:in `apply_system_config'
    from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.57/lib/fluent/supervisor.rb:110:in `initialize'
    from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.57/lib/fluent/command/fluentd.rb:168:in `new'
    from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.57/lib/fluent/command/fluentd.rb:168:in `<top (required)>'
    from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.57/bin/fluentd:6:in `<top (required)>'
    from /opt/td-agent/embedded/bin/fluentd:23:in `load'
    from /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
    from /usr/sbin/td-agent:7:in `load'
    from /usr/sbin/td-agent:7:in `<main>'
                                                           [失败]
```

![image](https://cloud.githubusercontent.com/assets/1734549/5136734/96d12398-7170-11e4-9729-ff1993a77839.png)

**Comment by Seraf** [comment]
Hello @y-ken,

First, thanks for this plugin :)

I have a similar problem, my geoip field is well declared in my mapping, but have trouve with td-agent 2.2.0 to declare a json : 

```
<match **.access>
  type geoip
  geoip_lookup_key  remote

  # Specify optional geoip database (using bundled GeoLiteCity databse by default)
  geoip_database    "/opt/td-agent/GeoLiteCity.dat"

  # Set adding field with placeholder (more than one settings are required.)
  <record>
    geoip            "{'coordinates':[${latitude['remote']},${longitude['remote']}],'country':${country_code['remote']}}"
  </record>

  # Settings for tag
  tag               ${tag}.geoip
</match>
```

It leads me to a ``` 2015-05-18 20:59:37 +0200 [error]: dry run failed: geoip: failed to parse '{'coordinates':[${latitude['remote']},${longitude['remote']}],'country':${country_code['remote']}}' as json.
```
I've done many test of escaping, but didn't achieved to make it work. Can you help me please ? (also I guess it would be a good thing to provide a configuration working out of box with kibana 4 as an example).

Thanks !

**Comment by repeatedly** [comment]
From [README](https://github.com/y-ken/fluent-plugin-geoip#advanced-config-samples), you should use `"` instead of `'`. JSON's string is quoted by `"`.
Following configuration works on my environment.

```aconf
<match test.**>
  type geoip
  geoip_lookup_key remote

  # Specify optional geoip database (using bundled GeoLiteCity databse by default)
  geoip_database "/opt/td-agent/GeoLiteCity.dat"

  # Set adding field with placeholder (more than one settings are required.)
  <record>
    geoip '{"coordinates":[${latitude["remote"]},${longitude["remote"]}],"country":${country_code["remote"]}}'
  </record>

  # Settings for tag
  tag ${tag}.geoip
</match>
```

**Comment by Seraf** [comment]
@repeatedly oh, sorry you're right... I don't know why, I was sure to already have tried this.
Using your example, it works on my side and working with kibana4.

Thanks a lot :)

**Comment by dperetti** [comment]
The README should be updated with @repeatedly 's hint !

**Comment by dperetti** [comment]
Well except that I think @repeatedly has swapped latitude and longitude. It should be :
```
<record>
    geoip           '{"location":[${longitude["remote"]},${latitude["remote"]}],"country":${country_code["remote"]}}'
</record>
```

At least that's what I need to get plots rights in Kibana 4.

**Comment by hydnwang** [comment]
@dperetti is right!
refer to this: https://www.elastic.co/guide/en/elasticsearch/guide/current/lat-lon-formats.html

The lat/lon order should be opposite in an array, such as "coordinates": [longitude, latitude].

**Comment by okkez** [comment]
README.md has already updated.
