### ISSUE TITLE
fluent-plugin-geoip / Ruby 2.7 / fluentd 4.1.1

### ISSUE THREAD

**Issue by devinatencio** [y-ken/fluent-plugin-geoip#93]
#### Problem

...

#### Steps to replicate

Provide example config and message
```
<filter haproxy.**>
  @type geoip

  # Specify one or more geoip lookup field which has ip address (default: host)
  geoip_lookup_keys  c_ip

  # Specify optional geoip database (using bundled GeoLiteCity databse by default)
  # geoip_database    "/path/to/your/GeoIPCity.dat"
  # Specify optional geoip2 database (using bundled GeoLite2 database by default)
  geoip2_database   "/usr/share/GeoIP/GeoLite2-City.mmdb"
  # Specify backend library (geoip2_c, geoip, geoip2_compat)
  backend_library geoip2_c

  # Set adding field with placeholder (more than one settings are required.)
  <record>
    city            ${city.names.en["c_ip"]}
    latitude        ${location.latitude["c_ip"]}
    longitude       ${location.longitude["c_ip"]}
    country         ${country.iso_code["c_ip"]}
    country_name    ${country.names.en["c_ip"]}
    postal_code     ${postal.code["c_ip"]}
    region_code     ${subdivisions.0.iso_code["c_ip"]}
    region_name     ${subdivisions.0.names.en["c_ip"]}
  </record>

  # To avoid get stacktrace error with `[null, null]` array for elasticsearch.
  skip_adding_null_record  true
</filter>
```

```
Jul 30 21:24:46 fluentd-dr.banksiteservices.co fluentd[29565]: /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-geoip-1.3.2/lib/fluent/plugin/filter_geoip.rb:213:in `load_database': uninitialized constant>
Jul 30 21:24:46 fluentd-dr.banksiteservices.co fluentd[29565]: Did you mean?  Geoip2
Jul 30 21:24:46 fluentd-dr.banksiteservices.co fluentd[29565]:         from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-geoip-1.3.2/lib/fluent/plugin/filter_geoip.rb:103:in `configure'
Jul 30 21:24:46 fluentd-dr.banksiteservices.co fluentd[29565]:         from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin.rb:178:in `configure'
Jul 30 21:24:46 fluentd-dr.banksiteservices.co fluentd[29565]:         from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/agent.rb:154:in `add_filter'
Jul 30 21:24:46 fluentd-dr.banksiteservices.co fluentd[29565]:         from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/agent.rb:72:in `block in configure'
Jul 30 21:24:46 fluentd-dr.banksiteservices.co fluentd[29565]:         from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/agent.rb:64:in `each'
Jul 30 21:24:46 fluentd-dr.banksiteservices.co fluentd[29565]:         from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/agent.rb:64:in `configure'
Jul 30 21:24:46 fluentd-dr.banksiteservices.co fluentd[29565]:         from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/root_agent.rb:146:in `configure'
Jul 30 21:24:46 fluentd-dr.banksiteservices.co fluentd[29565]:         from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/engine.rb:105:in `configure'
Jul 30 21:24:46 fluentd-dr.banksiteservices.co fluentd[29565]:         from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/engine.rb:80:in `run_configure'
Jul 30 21:24:46 fluentd-dr.banksiteservices.co fluentd[29565]:         from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/supervisor.rb:648:in `run_supervisor'
Jul 30 21:24:46 fluentd-dr.banksiteservices.co fluentd[29565]:         from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/command/fluentd.rb:345:in `<top (required)>'
Jul 30 21:24:46 fluentd-dr.banksiteservices.co fluentd[29565]:         from /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
Jul 30 21:24:46 fluentd-dr.banksiteservices.co fluentd[29565]:         from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/bin/fluentd:8:in `<top (required)>'
Jul 30 21:24:46 fluentd-dr.banksiteservices.co fluentd[29565]:         from /opt/td-agent/bin/fluentd:23:in `load'
Jul 30 21:24:46 fluentd-dr.banksiteservices.co fluentd[29565]:         from /opt/td-agent/bin/fluentd:23:in `<main>'
```

#### Expected Behavior

Using td-agent 3.8 / plugin works just fine on CentOS 7, however when i migrated to new CentOS 8.4, using latest td-agent and plugin, crashes on start.

Appears trying to migrate to latest td-agent which uses newer version of Ruby creates issues with plugin?
...

#### Your environment

* OS version:
CentOS 8.4

* paste result of ``fluentd --version`` or ``td-agent --version``
 ```
td-agent 4.1.1 fluentd 1.12.3 (b6e76c09d60ee866de6470f2bdd2551e7c8591d3)
```
* plugin version
```
fluent-plugin-geoip (1.3.2)
```
 * paste boot log of fluentd or td-agent

  * paste result of ``fluent-gem list``, ``td-agent-gem list`` or your Gemfile.lock
```  
activesupport (6.1.4)
addressable (2.7.0)
async (1.29.0)
async-http (0.54.1)
async-io (1.30.2)
async-pool (0.3.5)
aws-eventstream (1.1.1)
aws-partitions (1.446.0)
aws-sdk-core (3.114.0)
aws-sdk-kms (1.43.0)
aws-sdk-s3 (1.93.1)
aws-sdk-sqs (1.38.0)
aws-sigv4 (1.2.3)
benchmark (default: 0.1.0)
bigdecimal (default: 2.0.0)
bindata (2.4.9)
bundler (2.2.16, default: 2.1.4)
cgi (default: 0.1.0)
concurrent-ruby (1.1.8)
console (1.11.1)
cool.io (1.7.1)
csv (default: 3.1.2)
date (default: 3.0.0)
delegate (default: 0.1.0)
did_you_mean (default: 1.4.0)
dig_rb (1.0.1)
digest-crc (0.6.3)
elasticsearch (7.12.0)
elasticsearch-api (7.12.0)
elasticsearch-transport (7.12.0)
etc (default: 1.1.0)
ethon (0.14.0)
excon (0.80.1)
faraday (1.4.1)
faraday-excon (1.1.0)
faraday-net_http (1.0.1)
faraday-net_http_persistent (1.1.0)
faraday_middleware (1.0.0)
fcntl (default: 1.0.0)
ffi (1.15.0)
fiber-local (1.0.0)
fiddle (default: 1.0.0)
fileutils (1.5.0, default: 1.4.1)
fluent-config-regexp-type (1.0.0)
fluent-diagtool (1.0.1)
fluent-logger (0.9.0)
fluent-plugin-elasticsearch (5.0.3)
fluent-plugin-flowcounter-simple (0.1.0)
fluent-plugin-geoip (1.3.2)
fluent-plugin-haproxy (0.1.1)
fluent-plugin-kafka (0.16.1)
fluent-plugin-prometheus (1.8.5)
fluent-plugin-prometheus_pushgateway (0.0.2)
fluent-plugin-record-modifier (2.1.0)
fluent-plugin-rewrite-tag-filter (2.4.0)
fluent-plugin-s3 (1.6.0)
fluent-plugin-sd-dns (0.1.0)
fluent-plugin-systemd (1.0.2)
fluent-plugin-td (1.1.0)
fluent-plugin-utmpx (0.5.0)
fluent-plugin-webhdfs (1.4.0)
fluentd (1.12.3)
forwardable (default: 1.3.1)
geoip (1.6.4)
geoip-c (0.9.1)
geoip2 (0.0.3)
geoip2_c (0.3.3)
getoptlong (default: 0.1.0)
hashie (4.1.0)
hirb (0.7.3)
http_parser.rb (0.6.0)
httpclient (2.8.3)
i18n (1.8.10)
io-console (default: 0.5.6)
ipaddr (default: 1.2.2)
irb (default: 1.2.6)
jmespath (1.4.0)
json (2.5.1, default: 2.3.0)
linux-utmpx (0.3.0)
logger (default: 1.4.2)
ltsv (0.1.2)
matrix (default: 0.2.0)
mini_portile2 (2.5.0)
minitest (5.13.0)
msgpack (1.4.2)
multi_json (1.15.0)
multipart-post (2.1.1)
mutex_m (default: 0.1.0)
net-pop (default: 0.1.0)
net-smtp (default: 0.1.0)
net-telnet (0.2.0)
nio4r (2.5.7)
nokogiri (1.11.3 x86_64-linux)
observer (default: 0.1.0)
oj (3.11.5)
open3 (default: 0.1.0)
openssl (default: 2.1.2)
ostruct (default: 0.2.0)
parallel (1.20.1)
power_assert (1.1.7)
prime (default: 0.1.1)
prometheus-client (0.9.0)
protocol-hpack (1.4.2)
protocol-http (0.21.0)
protocol-http1 (0.13.2)
protocol-http2 (0.14.2)
pstore (default: 0.1.0)
psych (default: 3.1.0)
public_suffix (4.0.6)
quantile (0.2.1)
racc (1.5.2, default: 1.4.16)
rake (13.0.3, 13.0.1)
rdkafka (0.8.1)
rdoc (default: 6.2.1)
readline (default: 0.0.2)
readline-ext (default: 0.1.0)
reline (default: 0.1.5)
rexml (default: 3.2.3.1)
rss (default: 0.2.8)
ruby-kafka (1.3.0)
ruby-progressbar (1.11.0)
ruby2_keywords (0.0.4)
rubyzip (1.3.0)
sdbm (default: 1.0.0)
serverengine (2.2.3)
sigdump (0.2.4)
singleton (default: 0.1.0)
stringio (default: 0.1.0)
strptime (0.2.5)
strscan (default: 1.0.3)
systemd-journal (1.3.3)
td (0.16.9)
td-client (1.0.8)
td-logger (0.3.27)
test-unit (3.3.4)
timeout (default: 0.1.0)
timers (4.3.3)
tracer (default: 0.1.0)
typhoeus (1.4.0)
tzinfo (2.0.4)
tzinfo-data (1.2021.1)
uri (default: 0.10.0)
webhdfs (0.9.0)
webrick (1.7.0, default: 1.6.1)
xmlrpc (0.3.0)
yajl-ruby (1.4.1)
yaml (default: 0.1.0)
zeitwerk (2.4.2)
zip-zip (0.3)
zlib (default: 1.1.0)
```

**Comment by devinatencio** [comment]
I redeployed with a new VM image and didn't experience the same issue.
