### ISSUE TITLE
getaddrinfo failed: Name or service not known

### ISSUE THREAD

**Issue by CalvinVoxox** [y-ken/fluent-plugin-geoip#95]
#### Problem
dump an error event: error_class=GeoIP2::Error error="getaddrinfo failed: Name or service not known" location="/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-geoip-1.3.2/lib/fluent/plugin/filter_geoip.rb:178:in `lookup'"

#### Steps to replicate

Populate geoip_lookup_key field with a hostname that does not resolve, e.g. "NA". In our case, the IP fields do not always have a valid IP or FQDN.

Provide example config and message

  <filter **>
    @type geoip
    @id geoip_asn_term_sip
    geoip2_database "/usr/share/GeoIP/GeoLite2-ASN.mmdb"
    geoip_lookup_keys [ "Termination_Destination_Host_Name" ]
    <record>
      Term_Dst_SIP_ASN.asn ${autonomous_system_number["Termination_Destination_Host_Name"]}
      Term_Dst_SIP_ASN.as_org ${autonomous_system_organization["Termination_Destination_Host_Name"]}
    </record>
    # To avoid get stacktrace error with `[null, null]` array for elasticsearch.
    skip_adding_null_record true
  </filter>

2022-08-30 00:31:02 +0000 [warn]: #0 dump an error event: error_class=GeoIP2::Error error="getaddrinfo failed: Name or service not known" location="/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-geoip-1.3.2/lib/fluent/plugin/filter_geoip.rb:178:in `lookup'" tag="vsxi" time=2022-08-30 00:20:59.000000000 +0000 record={"Termination_Destination_Host_Name"=>"NA"}

#### Expected Behavior

Leave the record as-is and continue processing. Apply the same treatment as "skip_adding_null_record true" or add records with NULL values.

#### Your environment

* OS version 18.04.5 LTS (Bionic Beaver)
td-agent 4.4.1 fluentd 1.15.2 (c32842297ed2c306f1b841a8f6e55bdd0f1cb27f)

* plugin version
gem 'fluent-plugin-geoip' version '1.3.2'

  * paste boot log of fluentd or td-agent
2022-08-30 00:30:58 +0000 [info]: parsing config file is succeeded path="/etc/td-agent/td-agent.conf"
2022-08-30 00:30:58 +0000 [info]: gem 'fluent-plugin-calyptia-monitoring' version '0.1.3'
2022-08-30 00:30:58 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '5.2.3'
2022-08-30 00:30:58 +0000 [info]: gem 'fluent-plugin-flowcounter-simple' version '0.1.0'
2022-08-30 00:30:58 +0000 [info]: gem 'fluent-plugin-geoip' version '1.3.2'
2022-08-30 00:30:58 +0000 [info]: gem 'fluent-plugin-kafka' version '0.18.1'
2022-08-30 00:30:58 +0000 [info]: gem 'fluent-plugin-metrics-cmetrics' version '0.1.2'
2022-08-30 00:30:58 +0000 [info]: gem 'fluent-plugin-opensearch' version '1.0.8'
2022-08-30 00:30:58 +0000 [info]: gem 'fluent-plugin-opensearch' version '1.0.7'
2022-08-30 00:30:58 +0000 [info]: gem 'fluent-plugin-prometheus' version '2.0.3'
2022-08-30 00:30:58 +0000 [info]: gem 'fluent-plugin-prometheus_pushgateway' version '0.1.0'
2022-08-30 00:30:58 +0000 [info]: gem 'fluent-plugin-record-modifier' version '2.1.0'
2022-08-30 00:30:58 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.4.0'
2022-08-30 00:30:58 +0000 [info]: gem 'fluent-plugin-s3' version '1.7.1'
2022-08-30 00:30:58 +0000 [info]: gem 'fluent-plugin-sd-dns' version '0.1.0'
2022-08-30 00:30:58 +0000 [info]: gem 'fluent-plugin-systemd' version '1.0.5'
2022-08-30 00:30:58 +0000 [info]: gem 'fluent-plugin-td' version '1.2.0'
2022-08-30 00:30:58 +0000 [info]: gem 'fluent-plugin-utmpx' version '0.5.0'
2022-08-30 00:30:58 +0000 [info]: gem 'fluent-plugin-webhdfs' version '1.5.0'
2022-08-30 00:30:58 +0000 [info]: gem 'fluentd' version '1.15.2'
2022-08-30 00:30:59 +0000 [info]: using configuration file: <ROOT>
  <source>
    @type tail
    @id input_vsxi
    @label @VSXI
    @log_level "debug"
    tag "vsxi"
    path "/exports/crab/vsxi/test.cdr"
    path_key "file_path"
    pos_file "/var/log/td-agent/vsxi.pos"
    refresh_interval 60
    follow_inodes true
    read_from_head true
    rotate_wait 1
    enable_watch_timer false
    <parse>
      @type "csv"
      parser_type fast
      delimiter ";"
      keys ["Record_Sequence_Number","Version_Number","Record_Type","Connection_Type","Session_ID","Release_Cause","Start_Time_of_Date","Answer_Time_of_Date","Release_Time_of_Date","Minutes_West_of_Greenwich_Mean_Time","Release_Cause_from_Protocol_Stack","Binary_Value_of_Release_Cause_from_Protocol_stack","First_Release_Dialog","Trunk_ID_Origination","VoIP_Protocol_Origination","Origination_Source_Number","Origination_Source_Host_Name","Origination_Destination_Number","Origination_Destination_Host_Name","Origination_Call_ID","Origination_Remote_Payload_IP_Address","Origination_Remote_Payload_UDP_Port","Origination_Local_Payload_IP_Address","Origination_Local_Payload_UDP_Port","Origination_Codec_List","Origination_Ingress_Packets","Origination_Egress_Packets","Origination_Ingress_Octets","Origination_Egress_Octets","Origination_Ingress_Packet_Loss","Origination_Ingress_Delay","Origination_Ingress_Packet_Jitter","Trunk_ID_Termination","VoIP_Protocol_Termination","Termination_Source_Number","Termination_Source_Host_Name","Termination_Destination_Number","Termination_Destination_Host_Name","Termination_Call_ID","Termination_Remote_Payload_IP_Address","Termination_Remote_Payload_UDP_Port","Termination_Local_Payload_IP_Address","Termination_Local_Payload_UDP_Port","Termination_Codec_List","Termination_Ingress_Packets","Termination_Egress_Packets","Termination_Ingress_Octets","Termination_Egress_Octets","Termination_Ingress_Packet_Loss","Termination_Ingress_Delay","Termination_Ingress_Packet_Jitter","Final_Route_Indication","Routing_Digits","Call_Duration_in_Seconds","Origination_Post_Dial_Delay_in_Seconds","Ring_Time_in_Seconds","Duration_in_Milliseconds","Conf_ID","RPID_PAI","Route_Entry_Index","Route_Table_Used","LNP_Dipped","Ingress_LRN","Egress_LRN","CNAM_Dipped","DNC_Dipped","Origination_TID_Alias_Name","Termination_TID_Alias_Name","External_Route_Server_Dipped","OLI_Digits","Routing_Match","Termination_PDD_in_milliseconds","P_Charge_Info","JIP","Matched_Digits_in_ERS","Route_Table_in_ERS","Route_Sequence_number_in_ERS","Jurisdiction_Type_used_in_ERS","Reason_Cause_Value_from_Protocol_Stack","Mapped_Cause_Code","Mapped_Reason_Cause_Value","Reason_Cause_Text_from_Protocol_Stack","Diversion_History_Info","Origination_Burst_Loss_Count","Origination_MOS","Origination_R_Factor","Termination_Burst_Loss_Count","Termination_MOS","Temination_R_Factor","Transcoding","Origination_SRTP","Termination_SRTP","FAS","FAS_Idle","Ingress_STI_Identity_Header","STI-AS_Signature_Result","Egress_STI_Identity_Header","STI-VS_Verification_Result","Customer_Rate","Vendor_Rate","STI-AS_origid","trailing_delimiter"]
      types Binary_Value_of_Release_Cause_from_Protocol_stack:integer, Call_Duration_in_Seconds:integer, Origination_Post_Dial_Delay_in_Seconds:integer, Ring_Time_in_Seconds:integer, Duration_in_Milliseconds:integer, Termination_PDD_in_milliseconds:integer, Route_Sequence_number_in_ERS:integer, Record_Sequence_Number:integer, Release_Cause:integer, Origination_Remote_Payload_UDP_Port:integer, Origination_Local_Payload_UDP_Port:integer, Origination_Ingress_Packets:integer, Origination_Egress_Packets:integer, Origination_Ingress_Octets:integer, Origination_Egress_Octets:integer, Origination_Ingress_Packet_Loss:integer, Origination_Ingress_Delay:integer, Origination_Ingress_Packet_Jitter:integer, Termination_Ingress_Packets:integer, Termination_Remote_Payload_UDP_Port:integer, Termination_Local_Payload_UDP_Port:integer, Termination_Egress_Packets:integer, Termination_Ingress_Octets:integer, Termination_Egress_Octets:integer, Termination_Ingress_Packet_Loss:integer, Termination_Ingress_Delay:integer, Termination_Ingress_Packet_Jitter:integer, Ingress_STI_Identity_Header:integer, Egress_STI_Identity_Header:integer
      time_key "Start_Time_of_Date"
      keep_time_key true
      time_type mixed
      time_format "%a %b %e  %H:%M:%S %Y"
      time_format_fallbacks %a %b %e %H:%M:%S %Y
      unmatched_lines
    </parse>
  </source>
  <label @VSXI>
    <filter **>
      @type geoip
      @id geoip_city_orig_sip
      geoip2_database "/usr/share/GeoIP/GeoLite2-City.mmdb"
      geoip_lookup_keys ["Origination_Source_Host_Name"]
      skip_adding_null_record true
      <record>
        Orig_Src_SIP_City.bettermap [${location.latitude["Origination_Source_Host_Name"]},${location.longitude["Origination_Remote_Payload_IP_Address"]}]
        Orig_Src_SIP_City.latitude ${location.latitude["Origination_Source_Host_Name"]}
        Orig_Src_SIP_City.longitude ${location.longitude["Origination_Source_Host_Name"]}
        Orig_Src_SIP_City.city_name ${city.names.en["Origination_Source_Host_Name"]}
        Orig_Src_SIP_City.continent_name ${continent.names.en["Origination_Source_Host_Name"]}
        Orig_Src_SIP_City.continent_code ${continent.code["Origination_Source_Host_Name"]}
        Orig_Src_SIP_City.country_code2 ${country.iso_code["Origination_Source_Host_Name"]}
        Orig_Src_SIP_City.country_name ${country.names.en["Origination_Source_Host_Name"]}
        Orig_Src_SIP_City.dma_code ${location.metro_code["Origination_Source_Host_Name"]}
        Orig_Src_SIP_City.postal_code ${postal.code["Origination_Source_Host_Name"]}
        Orig_Src_SIP_City.region_code ${subdivisions.iso_code["Origination_Source_Host_Name"]}
        Orig_Src_SIP_City.region_name ${subdivisions.names.en["Origination_Source_Host_Name"]}
        Orig_Src_SIP_City.timezone ${location.time_zone["Origination_Source_Host_Name"]}
      </record>
    </filter>
    <filter **>
      @type geoip
      @id geoip_city_orig_rtp
      geoip2_database "/usr/share/GeoIP/GeoLite2-City.mmdb"
      geoip_lookup_keys ["Origination_Remote_Payload_IP_Address"]
      skip_adding_null_record true
      <record>
        Orig_Src_RTP_City.bettermap [${location.latitude["Origination_Remote_Payload_IP_Address"]},${location.longitude["Origination_Remote_Payload_IP_Address"]}]
        Orig_Src_RTP_City.latitude ${location.latitude["Origination_Remote_Payload_IP_Address"]}
        Orig_Src_RTP_City.longitude ${location.longitude["Origination_Remote_Payload_IP_Address"]}
        Orig_Src_RTP_City.city_name ${city.names.en["Origination_Remote_Payload_IP_Address"]}
        Orig_Src_RTP_City.continent_name ${continent.names.en["Origination_Remote_Payload_IP_Address"]}
        Orig_Src_RTP_City.continent_code ${continent.code["Origination_Remote_Payload_IP_Address"]}
        Orig_Src_RTP_City.country_code2 ${country.iso_code["Origination_Remote_Payload_IP_Address"]}
        Orig_Src_RTP_City.country_name ${country.names.en["Origination_Remote_Payload_IP_Address"]}
        Orig_Src_RTP_City.dma_code ${location.metro_code["Origination_Remote_Payload_IP_Address"]}
        Orig_Src_RTP_City.postal_code ${postal.code["Origination_Remote_Payload_IP_Address"]}
        Orig_Src_RTP_City.region_code ${subdivisions.iso_code["Origination_Remote_Payload_IP_Address"]}
        Orig_Src_RTP_City.region_name ${subdivisions.names.en["Origination_Remote_Payload_IP_Address"]}
        Orig_Src_RTP_City.timezone ${location.time_zone["Origination_Remote_Payload_IP_Address"]}
      </record>
    </filter>
    <filter **>
      @type geoip
      @id geoip_city_term_sip
      geoip2_database "/usr/share/GeoIP/GeoLite2-City.mmdb"
      geoip_lookup_keys ["Termination_Destination_Host_Name"]
      skip_adding_null_record true
      <record>
        Term_Dst_SIP_City.bettermap [${location.latitude["Termination_Destination_Host_Name"]},${location.longitude["Termination_Destination_Host_Name"]}]
        Term_Dst_SIP_City.latitude ${location.latitude["Termination_Destination_Host_Name"]}
        Term_Dst_SIP_City.longitude ${location.longitude["Termination_Destination_Host_Name"]}
        Term_Dst_SIP_City.city_name ${city.names.en["Termination_Destination_Host_Name"]}
        Term_Dst_SIP_City.continent_name ${continent.names.en["Termination_Destination_Host_Name"]}
        Term_Dst_SIP_City.continent_code ${continent.code["Termination_Destination_Host_Name"]}
        Term_Dst_SIP_City.country_code2 ${country.iso_code["Termination_Destination_Host_Name"]}
        Term_Dst_SIP_City.country_name ${country.names.en["Termination_Destination_Host_Name"]}
        Term_Dst_SIP_City.dma_code ${location.metro_code["Termination_Destination_Host_Name"]}
        Term_Dst_SIP_City.postal_code ${postal.code["Termination_Destination_Host_Name"]}
        Term_Dst_SIP_City.region_code ${subdivisions.iso_code["Termination_Destination_Host_Name"]}
        Term_Dst_SIP_City.region_name ${subdivisions.names.en["Termination_Destination_Host_Name"]}
        Term_Dst_SIP_City.timezone ${location.time_zone["Termination_Destination_Host_Name"]}
      </record>
    </filter>
    <filter **>
      @type geoip
      @id geoip_city_term_rtp
      geoip2_database "/usr/share/GeoIP/GeoLite2-City.mmdb"
      geoip_lookup_keys ["Termination_Remote_Payload_IP_Address"]
      skip_adding_null_record true
      <record>
        Term_Dst_RTP_City.bettermap [${location.latitude["Termination_Remote_Payload_IP_Address"]},${location.longitude["Termination_Remote_Payload_IP_Address"]}]
        Term_Dst_RTP_City.latitude ${location.latitude["Termination_Remote_Payload_IP_Address"]}
        Term_Dst_RTP_City.longitude ${location.longitude["Termination_Remote_Payload_IP_Address"]}
        Term_Dst_RTP_City.city_name ${city.names.en["Termination_Remote_Payload_IP_Address"]}
        Term_Dst_RTP_City.continent_name ${continent.names.en["Termination_Remote_Payload_IP_Address"]}
        Term_Dst_RTP_City.continent_code ${continent.code["Termination_Remote_Payload_IP_Address"]}
        Term_Dst_RTP_City.country_code2 ${country.iso_code["Termination_Remote_Payload_IP_Address"]}
        Term_Dst_RTP_City.country_name ${country.names.en["Termination_Remote_Payload_IP_Address"]}
        Term_Dst_RTP_City.dma_code ${location.metro_code["Termination_Remote_Payload_IP_Address"]}
        Term_Dst_RTP_City.postal_code ${postal.code["Termination_Remote_Payload_IP_Address"]}
        Term_Dst_RTP_City.region_code ${subdivisions.iso_code["Termination_Remote_Payload_IP_Address"]}
        Term_Dst_RTP_City.region_name ${subdivisions.names.en["Termination_Remote_Payload_IP_Address"]}
        Term_Dst_RTP_City.timezone ${location.time_zone["Termination_Remote_Payload_IP_Address"]}
      </record>
    </filter>
    <filter **>
      @type geoip
      @id geoip_asn_orig_sip
      geoip2_database "/usr/share/GeoIP/GeoLite2-ASN.mmdb"
      geoip_lookup_keys ["Origination_Source_Host_Name"]
      skip_adding_null_record true
      <record>
        Orig_Src_SIP_ASN.asn ${autonomous_system_number["Origination_Source_Host_Name"]}
        Orig_Src_SIP_ASN.as_org ${autonomous_system_organization["Origination_Source_Host_Name"]}
      </record>
    </filter>
    <filter **>
      @type geoip
      @id geoip_asn_orig_rtp
      geoip2_database "/usr/share/GeoIP/GeoLite2-ASN.mmdb"
      geoip_lookup_keys ["Origination_Remote_Payload_IP_Address"]
      skip_adding_null_record true
      <record>
        Orig_Src_RTP_ASN.asn ${autonomous_system_number["Origination_Remote_Payload_IP_Address"]}
        Orig_Src_RTP_ASN.as_org ${autonomous_system_organization["Origination_Remote_Payload_IP_Address"]}
      </record>
    </filter>
    <filter **>
      @type geoip
      @id geoip_asn_term_sip
      geoip2_database "/usr/share/GeoIP/GeoLite2-ASN.mmdb"
      geoip_lookup_keys ["Termination_Destination_Host_Name"]
      skip_adding_null_record true
      <record>
        Term_Dst_SIP_ASN.asn ${autonomous_system_number["Termination_Destination_Host_Name"]}
        Term_Dst_SIP_ASN.as_org ${autonomous_system_organization["Termination_Destination_Host_Name"]}
      </record>
    </filter>
    <filter **>
      @type geoip
      @id geoip_asn_term_rtp
      geoip2_database "/usr/share/GeoIP/GeoLite2-ASN.mmdb"
      geoip_lookup_keys ["Termination_Remote_Payload_IP_Address"]
      skip_adding_null_record true
      <record>
        Term_Dst_RTP_ASN.asn ${autonomous_system_number["Termination_Remote_Payload_IP_Address"]}
        Term_Dst_RTP_ASN.as_org ${autonomous_system_organization["Termination_Remote_Payload_IP_Address"]}
      </record>
    </filter>
    <filter **>
      @type record_modifier
      @id filter_remove_keys
      remove_keys "Version_Number,Record_Type,Minutes_West_of_Greenwich_Mean_Time,VoIP_Protocol_Origination,VoIP_Protocol_Termination,Route_Entry_Index,Route_Table_Used,LNP_Dipped,CNAM_Dipped,DNC_Dipped,External_Route_Server_Dipped,Origination_Burst_Loss_Count,Origination_MOS,Origination_R_Factor,Termination_Burst_Loss_Count,Termination_MOS,Temination_R_Factor,Transcoding,Origination_SRTP,Termination_SRTP,FAS,FAS_Idle,Customer_Rate,Vendor_Rate,trailing_delimiter"
    </filter>
    <match **>
      @type opensearch
      @id output_opensearch
      @log_level "debug"
      hosts "http://localhost:9200"
      index_name "rawcdrs-%Y.%m.%d"
      <buffer tag, time>
        timekey 1s
        timekey_wait 5s
      </buffer>
    </match>
  </label>
</ROOT>
2022-08-30 00:30:59 +0000 [info]: starting fluentd-1.15.2 pid=18301 ruby="2.7.6"
2022-08-30 00:30:59 +0000 [info]: spawn command to main:  cmdline=["/opt/td-agent/bin/ruby", "-Eascii-8bit:ascii-8bit", "/opt/td-agent/bin/fluentd", "--log", "/var/log/td-agent/td-agent.log", "--daemon", "/var/run/td-agent/td-agent.pid", "--under-supervisor"]
2022-08-30 00:31:00 +0000 [info]: adding filter in @VSXI pattern="**" type="geoip"
2022-08-30 00:31:00 +0000 [info]: adding filter in @VSXI pattern="**" type="geoip"
2022-08-30 00:31:00 +0000 [info]: adding filter in @VSXI pattern="**" type="geoip"
2022-08-30 00:31:00 +0000 [info]: adding filter in @VSXI pattern="**" type="geoip"
2022-08-30 00:31:00 +0000 [info]: adding filter in @VSXI pattern="**" type="geoip"
2022-08-30 00:31:00 +0000 [info]: adding filter in @VSXI pattern="**" type="geoip"
2022-08-30 00:31:00 +0000 [info]: adding filter in @VSXI pattern="**" type="geoip"
2022-08-30 00:31:00 +0000 [info]: adding filter in @VSXI pattern="**" type="geoip"
2022-08-30 00:31:00 +0000 [info]: adding filter in @VSXI pattern="**" type="record_modifier"
2022-08-30 00:31:00 +0000 [info]: adding match in @VSXI pattern="**" type="opensearch"
2022-08-30 00:31:01 +0000 [info]: adding source type="tail"
2022-08-30 00:31:01 +0000 [info]: #0 starting fluentd worker pid=18938 ppid=18935 worker=0
2022-08-30 00:31:01 +0000 [info]: #0 [input_vsxi] following tail of /exports/crab/vsxi/test.cdr

  * paste result of ``fluent-gem list``, ``td-agent-gem list`` or your Gemfile.lock

*** LOCAL GEMS ***

addressable (2.8.1)
async (1.30.3)
async-http (0.56.6)
async-io (1.33.0)
async-pool (0.3.11)
aws-eventstream (1.2.0)
aws-partitions (1.609.0)
aws-sdk-core (3.131.3)
aws-sdk-kms (1.58.0)
aws-sdk-s3 (1.114.0)
aws-sdk-sqs (1.51.1)
aws-sigv4 (1.5.1)
benchmark (default: 0.1.0)
bigdecimal (default: 2.0.0)
bindata (2.4.10)
bundler (2.3.18, default: 2.1.4)
cgi (default: 0.1.0.1)
cmetrics (0.3.3)
concurrent-ruby (1.1.10)
console (1.15.3)
cool.io (1.7.1)
csv (default: 3.1.2)
date (default: 3.0.3)
delegate (default: 0.1.0)
did_you_mean (default: 1.4.0)
dig_rb (1.0.1)
digest-crc (0.6.4)
digest-murmurhash (1.1.1)
elastic-transport (8.0.1)
elasticsearch (8.3.0)
elasticsearch-api (8.3.0)
etc (default: 1.1.0)
excon (0.92.4)
faraday (1.10.1)
faraday-em_http (1.0.0)
faraday-em_synchrony (1.0.0)
faraday-excon (1.1.0)
faraday-httpclient (1.0.1)
faraday-multipart (1.0.4)
faraday-net_http (1.0.1)
faraday-net_http_persistent (1.2.0)
faraday-patron (1.0.0)
faraday-rack (1.0.0)
faraday-retry (1.0.3)
faraday_middleware-aws-sigv4 (0.6.1)
fcntl (default: 1.0.0)
ffi (1.15.5)
fiber-local (1.0.0)
fiddle (default: 1.0.0)
fileutils (1.6.0, default: 1.4.1)
fluent-config-regexp-type (1.0.0)
fluent-diagtool (1.0.1)
fluent-logger (0.9.0)
fluent-plugin-calyptia-monitoring (0.1.3)
fluent-plugin-elasticsearch (5.2.3)
fluent-plugin-flowcounter-simple (0.1.0)
fluent-plugin-geoip (1.3.2)
fluent-plugin-kafka (0.18.1)
fluent-plugin-metrics-cmetrics (0.1.2)
fluent-plugin-opensearch (1.0.8, 1.0.7)
fluent-plugin-prometheus (2.0.3)
fluent-plugin-prometheus_pushgateway (0.1.0)
fluent-plugin-record-modifier (2.1.0)
fluent-plugin-rewrite-tag-filter (2.4.0)
fluent-plugin-s3 (1.7.1)
fluent-plugin-sd-dns (0.1.0)
fluent-plugin-systemd (1.0.5)
fluent-plugin-td (1.2.0)
fluent-plugin-utmpx (0.5.0)
fluent-plugin-webhdfs (1.5.0)
fluentd (1.15.2)
forwardable (default: 1.3.1)
geoip-c (0.9.1)
geoip2_c (0.3.3)
getoptlong (default: 0.1.0)
hirb (0.7.3)
http_parser.rb (0.8.0)
httpclient (2.8.3)
io-console (default: 0.5.6)
ipaddr (default: 1.2.2)
irb (default: 1.2.6)
jmespath (1.6.1)
json (2.6.2, default: 2.3.0)
linux-utmpx (0.3.0)
logger (default: 1.4.2)
ltsv (0.1.2)
matrix (default: 0.2.0)
mini_portile2 (2.8.0)
minitest (5.13.0)
msgpack (1.5.3)
multi_json (1.15.0)
multipart-post (2.2.3)
mutex_m (default: 0.1.0)
net-pop (default: 0.1.0)
net-smtp (default: 0.1.0)
net-telnet (0.2.0)
nio4r (2.5.8)
observer (default: 0.1.0)
oj (3.13.17)
open3 (default: 0.1.0)
opensearch-api (2.0.2)
opensearch-ruby (2.0.2)
opensearch-transport (2.0.0)
openssl (default: 2.1.3)
ostruct (default: 0.2.0)
parallel (1.22.1)
power_assert (1.1.7)
prime (default: 0.1.1)
prometheus-client (2.1.0)
protocol-hpack (1.4.2)
protocol-http (0.22.9)
protocol-http1 (0.14.4)
protocol-http2 (0.14.2)
pstore (default: 0.1.0)
psych (default: 3.1.0)
public_suffix (5.0.0)
racc (default: 1.4.16)
rake (13.0.6, 13.0.1)
rdkafka (0.11.1)
rdoc (default: 6.2.1.1)
readline (default: 0.0.2)
reline (default: 0.1.5)
rexml (default: 3.2.3.1)
rss (default: 0.2.8)
ruby-kafka (1.5.0)
ruby-progressbar (1.11.0)
ruby2_keywords (0.0.5)
rubyzip (1.3.0)
sdbm (default: 1.0.0)
serverengine (2.3.0)
sigdump (0.2.4)
singleton (default: 0.1.0)
stringio (default: 0.1.0)
strptime (0.2.5)
strscan (default: 1.0.3)
systemd-journal (1.4.2)
td (0.16.9)
td-client (1.0.8)
td-logger (0.3.28)
test-unit (3.3.4)
timeout (default: 0.1.0)
timers (4.3.3)
tracer (default: 0.1.0)
traces (0.4.1)
tzinfo (2.0.5)
tzinfo-data (1.2022.1)
uri (default: 0.10.0)
webhdfs (0.10.2)
webrick (1.7.0, default: 1.6.1)
xmlrpc (0.3.0)
yajl-ruby (1.4.3)
yaml (default: 0.1.0)
zip-zip (0.3)
zlib (default: 1.1.0)

**Comment by CalvinVoxox** [comment]
I had mistakenly assumed this plugin was performing a DNS lookup on any non-IP addresses, but on second look I see getaddrinfo is happening without any "gethostbyname" prior.

Our SBC will put an IP, fully qualified domain name, or "NA" in this field.
